### ISSUE TITLE
error in clove run on BEDPE

### ISSUE THREAD

**Issue by alkodsi** [PapenfussLab/clove#1]
Exception in thread "main" htsjdk.samtools.SAMFormatException: SAM validation error: ERROR: Record 147517, Read name HWI-EAS324_96694046:7:77:833:7#0, bin field of BAM record does not equal value computed based on alignment start and end, and length of sequence to which read is aligned
        at htsjdk.samtools.SAMUtils.processValidationErrors(SAMUtils.java:439)
        at htsjdk.samtools.BAMFileReader$BAMFileIterator.advance(BAMFileReader.java:644)
        at htsjdk.samtools.BAMFileReader$BAMFileIterator.next(BAMFileReader.java:629)
        at htsjdk.samtools.BAMFileReader$BAMFileIterator.next(BAMFileReader.java:599)
        at htsjdk.samtools.BAMFileReader$BAMQueryFilteringIterator.advance(BAMFileReader.java:832)
        at htsjdk.samtools.BAMFileReader$BAMQueryFilteringIterator.next(BAMFileReader.java:822)
        at htsjdk.samtools.BAMFileReader$BAMQueryFilteringIterator.next(BAMFileReader.java:788)
        at htsjdk.samtools.SamReader$AssertingIterator.next(SamReader.java:544)
        at htsjdk.samtools.SamReader$AssertingIterator.next(SamReader.java:518)
        at htsjdk.samtools.util.PeekableIterator.advance(PeekableIterator.java:68)
        at htsjdk.samtools.util.PeekableIterator.next(PeekableIterator.java:54)
        at htsjdk.samtools.filter.FilteringIterator.getNextRecord(FilteringIterator.java:130)
        at htsjdk.samtools.filter.FilteringIterator.next(FilteringIterator.java:105)
        at htsjdk.samtools.filter.FilteringIterator.next(FilteringIterator.java:45)
        at htsjdk.samtools.util.PeekableIterator.advance(PeekableIterator.java:68)
        at htsjdk.samtools.util.PeekableIterator.next(PeekableIterator.java:54)
        at htsjdk.samtools.util.SamLocusIterator.next(SamLocusIterator.java:317)
        at htsjdk.samtools.util.SamLocusIterator.hasNext(SamLocusIterator.java:240)
        at au.edu.wehi.clove.Clove.getReadDepth(Clove.java:450)
        at au.edu.wehi.clove.Clove.main(Clove.java:1238)

**Comment by alkodsi** [comment]
I also have some questions:
- Can I use gridss vcf output directly?
- Should I pass the normal bam together with the tumor bam?
- What does the mean coverage passed by -c mean?
- Most high quality gridss calls have failed in clove, how should I interpret clove output?

**Comment by d-cameron** [comment]
That error message is indicative of a malformed input BAM. You can force the bin field to be computed by converting the file to SAM, then back to BAM again.

Unfortunately, clove has not yet been updated to handle variants in VCF breakend notation.

@jibsch - can you comment on the clove parameters and usage?

**Comment by alkodsi** [comment]
I tried the conversion but it didn't work, same error. This is what I tried:
samtools view -h input.bam > input.sam
samtools view -b input.sam > output.bam

**Comment by jibsch** [comment]
GRIDSS VCF is now supported by CLOVE.

**Comment by NThio** [comment]
I'm trialling CLOVE on GRIDSS output, some minor things I noticed:

- the help message haven't included this feature yet, so you can specify gridss_output.vcf gridss ; where gridss is the algorithm,
- when using -r to skip read depth check, it always ended with null exception (eg. attempting to close samtools stream), it is outputted (presumably) correctly, as the exception thrown at the very end.
- the -r option was in the release note, but not in the help message.

Also previously before using GRIDSS vcf directly, I used GRIDSS bedpe (with column ordering) as CLOVE input, however the type seems to be either ITX1 or ITX2; outputs from using GRIDSS vcf directly seems to be more variety on the types - haven't had a closer look on it, but it seems better off using the vcf directly.

**Comment by jibsch** [comment]
Hi,
I've included the -r option silently, because a user asked for it specifically. 
I've added it to the set of regular options, since the number of interested user seems to be >1 :)
Gridss added to algorithm list as well.
I am not sure about the null pointer exception and stream closing error, as it does not reproduce for me. Some sample output would be helpful.
If there is a difference between the BEDPE and the VCF from GRIDSS, it is likely due to the parsing from the latter into the former, and not converting orientations correctly. How did you create the BEDPE?
Regards,
Jan
