### ISSUE TITLE
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException:

### ISSUE THREAD

**Issue by ptranvan** [PapenfussLab/clove#11]
Hi I have this problem after running this command:

`java -jar clove-0.17-jar-with-dependencies.jar -i ../De446W2_L1_001.vcf  GRIDSS -b ../../bwa_no_M/De446W2_L1_001.sorted.bam -c 13 10 -o De446W2_L1_001_clover.vcf
`
```
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
        at au.edu.wehi.clove.Event.classifyAltGridssLumpy(Event.java:660)
        at au.edu.wehi.clove.Event.createNewEventFromGRIDSSOutput(Event.java:584)
        at au.edu.wehi.clove.Clove.main(Clove.java:635)
```

**Comment by cagaser** [comment]
Hello, I am having the same issue. Has this been solved?

```
clove -i gridss.vcf.gz GRIDSS -b sample.markdup.bam -c 32 11 -o gridss.clove.vcf
Reading input...
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 1
        at au.edu.wehi.clove.Event.createNewEventFromGRIDSSOutput(Event.java:582)
        at au.edu.wehi.clove.Clove.main(Clove.java:635)
```

**Comment by lucare** [comment]
Hi,

I am having the same issue. Any ideas on how to resolve. 

java -jar clove-0.17-jar-with-dependencies.jar -i sample_gridss.vcf.gz GRIDSS -b sample.bam -c 30 7 -o sample_output.vcf
Reading input...
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
        at au.edu.wehi.clove.Event.createNewEventFromGRIDSSOutput(Event.java:582)
        at au.edu.wehi.clove.Clove.main(Clove.java:635)

**Comment by robertzeibich** [comment]
I am having the same issue and when I am using the GRIDSS VCF and when I am using the BEDPE, I am getting "Unable to parse input breakpoints". Is there a workaround? Help would be much appreciated.

**Comment by robertzeibich** [comment]
I was able to get CLOVE with the BEDPE running. I had to make sure that all the columns contain integer values.
